app/dashboard/models.py
from app import db
from datetime import datetime, timedelta
from flask_login import current_user

## Expences table
class Transactions(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    tr_type = db.Column(db.String(255), nullable=False)
    category = db.Column(db.String(255), nullable=False)
    amount = db.Column(db.Float)
    # TODO: make something with date_created
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    owner_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class MonthExpencesProfile():
    first_exps = 0
    first_date = datetime.utcnow()
    second_exps = 0
    second_date = first_date.replace(day=1) - timedelta(days=1)
    third_exps = 0
    third_date = second_date.replace(day=1) - timedelta(days=1)
    fourth_exps = 0
    fourth_date = third_date.replace(day=1) - timedelta(days=1)
    fifth_exps = 0
    fifth_date = fourth_date.replace(day=1) - timedelta(days=1)

    def __init__(self):
        exps = Transactions.query.filter_by(owner_id=current_user.id).order_by(Transactions.date_created.desc()).all()
        for exp in exps:
            if exp.date_created.utcnow().strftime("%Y-%m") == self.first_date.strftime("%Y-%m"):
                self.first_exps += exp.amount
            elif exp.date_created.utcnow().strftime("%Y-%m") == self.second_date.strftime("%Y-%m"):
                self.second_exps += exp.amount
            elif exp.date_created.utcnow().strftime("%Y-%m") == self.third_date.strftime("%Y-%m"):
                self.third_exps += exp.amount
            elif exp.date_created.utcnow().strftime("%Y-%m") == self.fourth_exps.strftime("%Y-%m"):
                self.fourth_exps += exp.amount
            elif exp.date_created.utcnow().strftime("%Y-%m") == self.fifth_date.strftime("%Y-%m"):
                self.fifth_exps += exp.amount
        
        exp_n = [self.first_exps, self.second_exps, self.third_exps, self.fourth_exps, self.fifth_exps]
        exp_d = [self.first_date.strftime("%B"), self.second_date.strftime("%B"), self.third_date.strftime("%B"), self.fourth_date.strftime("%B"), self.fifth_date.strftime("%B")]

        self._data = []
        for i in range(0, 5):
            if exp_n[i] != 0:
                self._data.append((exp_d[i], exp_n[i]))

    def __getitem__(self, position):
        return self._data[position]

class MonthExpencesDashboard():
    monthly_expences = 0
    prev_month_exps = 0
    pprev_month = (datetime.utcnow().replace(day=1) - timedelta(days=1)).replace(day=1) - timedelta(days=1)

    exps_per_category = {
        'FOOD': 0,
        'HOUSE': 0,
        'ENTER': 0,
        'TAX': 0,
        'TRAVELS': 0,
        'PETS': 0,
        'SHOPPING': 0,
        'TRANSPORT': 0,
        'MEDICINE': 0,
        'SUPPLIES': 0,
        'VEHICLE': 0,
        'COMMUNIC': 0,
        'INVESTMENT': 0,
        'INCOME': 0,
        'OTHER': 0,
    }

    def __init__(self) -> None:
        exps = Transactions.query.filter_by(owner_id=current_user.id).order_by(Transactions.date_created.desc()).all()
        for exp in exps:
            if exp.date_created.utcnow().strftime("%Y-%m") == datetime.utcnow().strftime("%Y-%m"):
                self.monthly_expences += exp.amount
                self.exps_per_category[exp.category] += exp.amount
            elif exp.date_created.utcnow().strftime("%Y-%m") != datetime.utcnow().strftime("%Y-%m") and exp.date_created.utcnow().strftime("%Y-%m") > self.pprev_month:
                self.prev_month_exps += exp.amount

        self._data = []
        for key in self.exps_per_category:
            if self.exps_per_category[key] != 0:
                self._data.append((key, self.exps_per_category[key]) )
    
    def __getitem__(self, position):
        return self._data[position]

    def monthly_exps(self):
        return self.monthly_expences

    def prev_monthly_exps(self):
        return self.prev_month_exps

app/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField, DecimalField
from flask_babel import _, lazy_gettext as _l
from enum import Enum

# Categories in SelectField
class Categories(Enum):
    FOOD = _l("Food & Drinks")
    HOUSE = _l("Housing")
    ENTER = _l("Entertainment")
    TAX = _l("Tax")
    TRAVELS = _l("Travels")
    PETS = _l("Pets")
    SHOPPING = _l("Shopping")
    TRANSPORT = _l("Transportation")
    MEDICINE = _l("Medicine")
    SUPPLIES = _l("Supplies")
    VEHICLE = _l("Vehicle")
    COMMUNIC = _l("Communication")
    INVESTMENT = _l("Investments")
    INCOME = _l("Income")
    OTHER = _l("Other")

    def __str__(self):
        return self.value

categories = [(y.name, _l(str(y.value))) for y in Categories]

# Form to add expence
class AddExpenceForm(FlaskForm):
    tr_type = SelectField(choices=[('Income', _l('Income')), ('Expense', _l('Expence'))])
    category_select = SelectField(choices=categories)
    amount = DecimalField('Amount', render_kw={"placeholder": _l('Amount')})
    submit = SubmitField(_l('Добавить'))

app/dashboard/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for, g, has_request_context
from app import db
from app.dashboard.models import Transactions, MonthExpencesProfile, MonthExpencesDashboard
from app.dashboard.forms import AddExpenceForm
from datetime import datetime, timedelta
from app import login_manager
from flask_login import login_required, current_user
from app.auth.models import User

board = Blueprint('dashboard', __name__, url_prefix='/<lang_code>')

@board.url_defaults
def add_language_code(endpoint, values):
    values.setdefault('lang_code', g.lang_code)

@board.url_value_preprocessor
def pull_lang_code(endpoint, values):
    g.lang_code = values.pop('lang_code')

# Login manager user loader 
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# Main dashboard route
@board.route('/')
@board.route('/dashboard', methods=['POST', 'GET'])
@login_required
def dashboard():
    
    form = AddExpenceForm()
    
    # Adding new items
    if form.validate_on_submit():
        new_item = Transactions(tr_type=form.tr_type.data, category=form.category_select.data, amount=form.amount.data, owner_id=current_user.id)
        db.session.add(new_item)
        db.session.commit()
        return redirect(url_for('dashboard.dashboard'))
    
    # Rendering everything out
    else:
        # Initializing db models
        page = request.args.get('page', 1, type=int)
        expences = Transactions.query.filter_by(owner_id=current_user.id).order_by(Transactions.date_created.desc()).paginate(per_page=5, page=page, error_out=True)
        
        # Calculating monthly expences
        data = MonthExpencesDashboard()

        monthly_expences = data.monthly_exps()
        prev_month_exps = data.prev_monthly_exps()

        labels = [row[0] for row in data]
        values = [row[1] for row in data]

        # Rendering
        return render_template(
            'dashboard/dashboard.html',
            expences=expences, form=form,
            prev_month = datetime.today().replace(day=1) - timedelta(days=1),
            monthly_expences=monthly_expences,
            prev_month_exps=prev_month_exps,
            labels=labels, values=values,
            username = current_user.username,
            data = data,
            date = datetime.utcnow()
            )

@board.route('/profile')
def profile():

    data = MonthExpencesProfile()

    labels = [row[0] for row in data]
    values = [row[1] for row in data]

    return render_template('dashboard/profile.html', labels=labels, values=values)

@board.route('/settings')
def settings():
    return render_template('dashboard/settings.html')

app/templates/dashboard/dashboard.html
{{ moment.include_moment()}}
{{ moment.locale(get_locale()) }}

<!DOCTYPE html>
<html lang="en">
      <!--
        DESIGNED BY OVLADAET
        INST: ovladaettt
    -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Budget - {{ _('Главная') }}</title>
    <link rel="stylesheet" type= "text/css" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" type= "text/css" href="{{ url_for('static', filename = 'css/reset-styles.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <!-- moment -->
</head>
<body>
  <!-- 19.09.2021 - Я еле нашел форму с вводом -->

    <!-- Экран загрузки -->
    <div class="preloader">
        <div class="preloader__row">
          <div class="preloader__item"></div>
          <div class="preloader__item"></div>
        </div>
      </div>
    <div class="personal-area">

        <!--Предупреждение о использлвании Cookie-->
        <div id="cookie_notification">
            <p>{{ _('Для улучшения работы сайта и его взаимодействия с пользователями мы используем файлы cookie. Продолжая работу с сайтом, Вы разрешаете использование cookie-файлов. Вы всегда можете отключить файлы cookie в настройках Вашего браузера.') }}</p>
            <button class="button cookie_accept">{{ _('Принять') }}</button>
    </div>

        <!--Левая колонка-->
        <div class="left-column">
            <h1>budget</h1>
            <ul>
                <li class="active"><a href="{{ url_for('dashboard.dashboard') }}"><img src="{{ url_for('static', filename= 'img/dashboard_white_24dp.svg') }}">&nbsp;{{ _('Главная') }}</a></li>
                <li><a href="{{ url_for('dashboard.profile') }}"><img src="{{ url_for('static', filename = 'img/account_circle_white_24dp.svg') }}">&nbsp;{{ _('Профиль') }}</a></li>
                <li><a href="{{ url_for('dashboard.settings') }}"><img src="{{ url_for('static', filename = 'img/settings_white_24dp.svg') }}">&nbsp;{{ _('Настройки') }}</a></li>
                <li><a href="{{ url_for('auth.signout') }}"><img src="{{ url_for('static', filename= 'img/logout_white_24dp.svg') }}">&nbsp;{{ _('Выйти') }}</a></li>
            </ul>
        </div>

        <!--Правая колонка-->
        <div class="right-column">

            <!--Верхняя панель-->
            <div class="top-nav">
                <h1>{{ _('Главная') }}</h1>
                <div class="mobile-menu">
                    <div class="open_img" id="open_img"><img onclick="open_mobile_menu()" src="{{ url_for('static', filename = 'img/menu_white_24dp.svg') }}" alt=""></div>
                    <div class="close_img" id="close_img"><img onclick="close_mobile_menu()" src="{{ url_for('static', filename = 'img/close_white_24dp.svg') }}" alt=""></div>
                </div>
                <div id="mobile-nav" class="mobile-navigation">
                    <ul>
                        <li class="active"><a href="{{ url_for('dashboard.dashboard') }}"><img src="{{ url_for('static', filename = 'img/dashboard_white_24dp.svg') }}">&nbsp;{{ _('Главная') }}</a></li>
                        <li><a href="{{ url_for('dashboard.profile') }}"><img src="{{ url_for('static', filename = 'img/account_circle_white_24dp.svg') }}">&nbsp;{{ _('Профиль') }}</a></li>
                        <li><a href="{{ url_for('dashboard.settings') }}"><img src="{{ url_for('static', filename = 'img/settings_white_24dp.svg') }}">&nbsp;{{ _('Настройки') }}</a></li>
                        <li><a href="{{ url_for('auth.signout') }}"><img src="{{ url_for('static', filename = 'img/logout_white_24dp.svg') }}">&nbsp;{{ _('Выйти') }}</a></li>
                    </ul>
                </div>
            </div>

            <!--Подсчет потраченных денег-->
            <div class="money-spent">
                <div class="money-spent-info">
                    <h1><b>{{ username }}</b>,{{ _('- вы потратили за') }} {{ moment(date).format('MMMM') }} {{  monthly_expences }} UAH</h1>
                    {% set previous = monthly_expences - prev_month_exps %}
                    {% if monthly_expences > prev_month_exps %}
                    <h2><img src="{{ url_for('static', filename = 'img/arrow_upward_black_24dp.svg') }}" alt="">
                    {{ previous }} UAH {{ _('по сравнению с ') }} {{ moment(prev_month).format('MMMM') }}</h2> 
                       <!--Вот стрелочка вниз--> 
                    {% else %}
                    <h2><img src="{{ url_for('static', filename = 'img/arrow_downward_black_24dp.svg') }}" alt=""></h2>
                    {{ previous }} UAH {{ _('по сравнению с ') }} <h1>&nbsp;</h1> {{ moment(prev_month).format('MMMM') }}</h2>
                    {% endif %}
                  </div>
                    <!--Диаграмма-->
                    <div class="chart">
                        <canvas id="myChart" width="200" height="200"></canvas>
                    </div>
                
            </div>
            <!--Кнопка добавления покупок-->
            <div class="add-purchase">
                <input onclick="open_adding_menu()" onmouseenter="on_mouse_enter()" onmouseleave="on_mouse_exit()" id="add-purchase" type="submit" class="add-button" value="+">
            </div>

            <!--Таблица затрат-->
        <div class="money-table">
          {% for day, expence in expences.items|groupby("date_created.day")|reverse %}
            <table>
              {% for exp in expence %}
                <tr><th colspan="4">{{ moment(exp.date_created).format('MMMM, D dddd') }}</th></tr>
                {% break %}
              {% endfor %}    
                    <tr>
                        <td>{{ _('Категория') }}</td>
                        <td>{{ _('Продукт') }}</td>
                        <td>{{ _('Цена') }}</td>
                        <td>{{ _('Время') }}</td>
                    </tr>
                    {% for exp in expence %}
                    <tr>
                        <td>{{ gettext(exp.tr_type) }}</td>
                        <td>{{ gettext(exp.category) }}</td>
                        <td>{{ exp.amount }} UAH</td>
                        <td>{{ moment(exp.date_created).format('LT') }}</td>
                    </tr>
                    {% endfor %}
            </table>
          {% endfor %}
        </div>

        <!--Переключение страниц-->
        <div class="pagination">
          <ul>
            {% for page_num in expences.iter_pages() %}
              {% if page_num %}
                {% if expences.page == page_num %}
                  <li class="page-active"><a href="{{ url_for('dashboard.dashboard', page=page_num) }}">{{ page_num }}</a></li>
                {% else %}
                  <li><a href="{{ url_for('dashboard.dashboard', page=page_num) }}" style="color: black;">{{ page_num }}</a></li>
                {% endif %}
              {% endif %}
            {% endfor %}
          </ul>
        </div>
    </div>  

        
        
    </div>
    

    <div id="layer">
        <div id="modal">
            <form method="POST">
              {{ form.hidden_tag() }}
              {{ form.tr_type }}<br>
              {{ form.category_select }}<br>
              {{ form.amount }}<br>
              {{ form.submit }}
            </form>
        </div>
    </div>

    <!-- Chart -->
    <script>
      var ctx = document.getElementById('myChart').getContext('2d');
      var myChart = new Chart(ctx, {
        type: 'doughnut',
        data: {
          labels: {{ labels | safe }},
          datasets: [{
            label: '# of Votes',
            data: {{ values | safe }},
            backgroundColor: [
                'rgba(255, 99, 132, 0.5)',
                'rgba(54, 162, 235, 0.5)',
                'rgba(255, 206, 86, 0.5)',
                'rgba(75, 192, 192, 0.5)',
                'rgba(153, 102, 255, 0.5)',
                'rgba(255, 159, 64, 0.5)'
            ]
          }]
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          plugins:{
            legend: {
              display: false
            }, 
          }   
        }
      });
    </script>

    <script src="{{ url_for('static', filename = 'js/profileScript.js') }}"></script>
    <script>
        // Эта шляпа плавно закрывает экран загрузки когда все прогрузилось
        window.onload = function () {
          document.body.classList.add('loaded_hiding');
          window.setTimeout(function () {
            document.body.classList.add('loaded');
            document.body.classList.remove('loaded_hiding');
          }, 500);
        }
      </script>
</body>
</html>

app/templates/dashboard/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--
        DESIGNED BY OVLADAET
        INST: ovladaettt
    -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Budget - {{ _('Профиль') }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/reset-styles.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
   <!-- Экран загрузки -->
    <div class="preloader">
        <div class="preloader__row">
          <div class="preloader__item"></div>
          <div class="preloader__item"></div>
        </div>
      </div>
    <div class="personal-area">
       <!--Левая колонка-->
       <div class="left-column">
        <h1>budget</h1>
        <ul>
            <li><a href="{{ url_for('dashboard.dashboard') }}"><img src="{{ url_for('static', filename = 'img/dashboard_white_24dp.svg') }}">&nbsp;{{ _('Главная') }}</a></li>
            <li class="active"><a href="{{ url_for('dashboard.profile') }}"><img src="{{ url_for('static', filename = 'img/account_circle_white_24dp.svg') }}">&nbsp;{{ _('Профиль') }}</a></li>
            <li><a href="{{ url_for('dashboard.settings') }}"><img src="{{ url_for('static', filename = 'img/settings_white_24dp.svg') }}">&nbsp;{{ _('Настройки') }}</a></li>
            <li><a href="{{ url_for('auth.signout') }}"><img src="{{ url_for('static', filename = 'img/logout_white_24dp.svg') }}">&nbsp;{{ _('Выйти') }}</a></li>
        </ul>
    </div>

        <!--Правая колонка-->
       
        <div class="right-column">
          
            <!--Верхняя панель-->
            <div class="top-nav">
                <h1>{{ _('Профиль') }}</h1>
                <div class="mobile-menu">
                    <div class="open_img" id="open_img"><img onclick="open_mobile_menu()" src="img/menu_white_24dp.svg" alt=""></div>
                    <div class="close_img" id="close_img"><img onclick="close_mobile_menu()" src="img/close_white_24dp.svg" alt=""></div>
                </div>
                <div id="mobile-nav" class="mobile-navigation">
                    <ul>
                        <li><a href="{{ url_for('dashboard.dashboard') }}"><img src="{{ url_for('static', filename = 'img/dashboard_white_24dp.svg') }}">&nbsp;{{ _('Главная') }}</a></li>
                        <li class="active"><a href="{{ url_for('dashboard.profile') }}"><img src="{{ url_for('static', filename = 'img/account_circle_white_24dp.svg') }}">&nbsp;{{ _('Профиль') }}</a></li>
                        <li><a href="{{ url_for('dashboard.settings') }}"><img src="{{ url_for('static', filename = 'img/settings_white_24dp.svg') }}">&nbsp;{{ _('Настройки') }}</a></li>
                        <li><a href="{{ url_for('auth.signout') }}"><img src="{{ url_for('static', filename = 'img/logout_white_24dp.svg') }}">&nbsp;{{ _('Выйти') }}</a></li>
                    </ul>
                </div>
            </div>

            <!-- Инфа -->
            <div class="right-centered">
            <div class="user-info">
                <h1 id="hello"></h1>
                <div class="money-per-month">
                    <h1>{{ _('Затраты за этот месяц') }} - {{ labels[0] }} UAH</h1><hr>
                </div>
            <!--Диаграмма-->
            <div class="chart">
                <canvas id="profile-Chart" width="200" height="200"></canvas>
            </div></div>
        </div>
        </div>
    <script src="{{ url_for('static', filename = 'js/profileScript.js') }}"></script>
    <script>
        var ctx = document.getElementById('profile-Chart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: {{ labels | safe }},
                datasets: [{
                    label: 'Потрачено UAH',
                    data: {{ values | safe }},
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins:{
                  legend: {
                    display: false
                    },
                }   
            }
        });
        
        
        
    </script>
    
<script>

window.onload = function () {
          document.body.classList.add('loaded_hiding');
          window.setTimeout(function () {
            document.body.classList.add('loaded');
            document.body.classList.remove('loaded_hiding');
          }, 500);
        }


function checkTime(i)
{
    if(i<10){
        i="0"+ i;
    }
    return i;
}
var t = new Date();

var text = document.getElementById("hello");

if(checkTime(t.getHours()) >= 6 && checkTime(t.getHours()) <= 12){
    text.innerHTML = "{{ _('Доброе утро!') }}";
}
else if(checkTime(t.getHours()) > 12 && checkTime(t.getHours()) <= 18){
    text.innerHTML = "{{ _('Добрый день!') }}";
}
else if(checkTime(t.getHours()) > 18 && checkTime(t.getHours()) <= 24){
    text.innerHTML = "{{ _('Добрый вечер!') }}";
}
else{
    text.innerHTML = "{{ _('Доброй ночи!') }}";
}
      
document.getElementById("close_img").hidden = true;
document.getElementById("mobile-nav").hidden = true;
function open_mobile_menu(){
    document.getElementById("mobile-nav").hidden = false;
    document.getElementById("close_img").hidden = false;
    document.getElementById("open_img").hidden = true;
}

function close_mobile_menu(){
    document.getElementById("mobile-nav").hidden = true;
    document.getElementById("close_img").hidden = true;
    document.getElementById("open_img").hidden = false;
}

</script>
</body>
</html>

app/templates/dashboard/settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--
        DESIGNED BY OVLADAET
        INST: ovladaettt
    -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Budget - {{ _('Настройки') }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/reset-styles.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <!-- Экран загрузки -->
    <div class="preloader">
        <div class="preloader__row">
          <div class="preloader__item"></div>
          <div class="preloader__item"></div>
        </div>
      </div>

    <div class="personal-area">
       <!--Левая колонка-->
       <div class="left-column">
        <h1>budget</h1>
        <ul>
            <li><a href="{{ url_for('dashboard.dashboard') }}"><img src="{{ url_for('static', filename = 'img/dashboard_white_24dp.svg') }}">&nbsp;{{ _('Главная') }}</a></li>
            <li><a href="{{ url_for('dashboard.profile') }}"><img src="{{ url_for('static', filename = 'img/account_circle_white_24dp.svg') }}">&nbsp;{{ _('Профиль') }}</a></li>
            <li class="active"><a href="{{ url_for('dashboard.settings') }}"><img src="{{ url_for('static', filename = 'img/settings_white_24dp.svg') }}">&nbsp;{{ _('Настройки') }}</a></li>
            <li><a href="{{ url_for('auth.signout') }}"><img src="{{ url_for('static', filename = 'img/logout_white_24dp.svg') }}">&nbsp;{{ _('Выйти') }}</a></li>
        </ul>
    </div>

        <!--Правая колонка-->
       
        <div class="right-column">
          
            <!--Верхняя панель-->
            <div class="top-nav">
                <h1>{{ _('Настройки') }}</h1>
                <div class="mobile-menu">
                    <div class="open_img" id="open_img"><img onclick="open_mobile_menu()" src="{{ url_for('static', filename = 'img/menu_white_24dp.svg') }}" alt=""></div>
                    <div class="close_img" id="close_img"><img onclick="close_mobile_menu()" src="{{ url_for('static', filename = 'img/close_white_24dp.svg') }}" alt=""></div>
                </div>
                <div id="mobile-nav" class="mobile-navigation">
                    <ul>
                        <li><a href="{{ url_for('dashboard.dashboard') }}"><img src="{{ url_for('static', filename = 'img/dashboard_white_24dp.svg') }}">&nbsp;{{ _('Главная') }}</a></li>
                        <li><a href="{{ url_for('dashboard.profile') }}"><img src="{{ url_for('static', filename = 'img/account_circle_white_24dp.svg') }}">&nbsp;{{ _('Профиль') }}</a></li>
                        <li class="active"><a href="{{ url_for('dashboard.settings') }}"><img src="{{ url_for('static', filename = 'img/settings_white_24dp.svg') }}">&nbsp;{{ _('Настройки') }}</a></li>
                        <li><a href="{{ url_for('auth.signout') }}"><img src="{{ url_for('static', filename = 'img/logout_white_24dp.svg') }}">&nbsp;{{ _('Выйти') }}</a></li>
                    </ul>
                </div>
            </div>
            <div class="settings-title"><h1>{{ _('Настройки') }}</h1></div>
            <div class="lang-select">
                <h1>{{ _('Язык') }}:</h1>
                <h1><a href="{{ url_for(request.endpoint, lang_code='en') }}">English</a></h1>
                <h1><a href="{{ url_for(request.endpoint, lang_code='de') }}">Deutsch</a></h1>
                <h1><a href="{{ url_for(request.endpoint, lang_code='uk') }}">Украинский</a></h1>
            </div>
        </div>
    </div>
<div>
    
</div>

    <script src="{{ url_for('static', filename = 'js/profileScript.js') }}"></script>
    <script>
        
document.getElementById("close_img").hidden = true;
document.getElementById("mobile-nav").hidden = true;
function open_mobile_menu(){
    document.getElementById("mobile-nav").hidden = false;
    document.getElementById("close_img").hidden = false;
    document.getElementById("open_img").hidden = true;
}

function close_mobile_menu(){
    document.getElementById("mobile-nav").hidden = true;
    document.getElementById("close_img").hidden = true;
    document.getElementById("open_img").hidden = false;
}

        window.onload = function () {
          document.body.classList.add('loaded_hiding');
          window.setTimeout(function () {
            document.body.classList.add('loaded');
            document.body.classList.remove('loaded_hiding');
          }, 500);
        }


    </script>
</body>
</html>